apiVersion: v1
kind: Secret
metadata:
  name: umap-env
type: Opaque
stringData:
  DATABASE_URL: "CHANGE_ME"
  REDIS_URL: "CHANGE_ME"
  STATIC_ROOT: "/srv/umap/static"
  MEDIA_ROOT: "/srv/umap/uploads"
  ENABLE_ACCOUNT_LOGIN: "1"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "CHANGE_ME"
  EMAIL_PORT: "CHANGE_ME"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "CHANGE_ME"
  EMAIL_HOST_PASSWORD: "CHANGE_ME"
  DEFAULT_FROM_EMAIL: "CHANGE_ME"
  SECRET_KEY: "CHANGE_ME"
  UMAP_SETTINGS: "/etc/umap/umap.conf"
